### ISSUE TITLE
No ActionRefinment possible

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#457] opened 2021-06-15 16:11 UTC
The current Shape for ids:Rule does not allow any refinement but strictly asks for a known instance of the ids:Action class:
https://github.com/International-Data-Spaces-Association/InformationModel/blob/22d8582acf85fcaafbfc1ff6ab27bd03e3ea8b40/testing/contract/RuleShape.ttl#L45

We need to add an alternative pattern to use the properties ids:actionRefinement etc.

**Comment by changqin26** [comment] 2021-07-26 13:27
Sorry, I just noticed this issue assigned to me. 
We have ids:actionRefinement for ids:Action class. Then ids:Rule can further define refinement through this. 

what are you referring to with "an alternative pattern"?

**Comment by changqin26** [comment] 2022-05-19 08:53
Hi @sebbader , is this requirement still required? If yes, can you please give me a use case?

**Comment by changqin26** [comment] 2022-06-30 11:30
The issue is closed because there is no latest update. Please feel free to reopen if the issue needs to be further solved.

**Closed by changqin26** 2022-06-30 11:30 UTC
Labels: bug
